<?php
$user = ['name' => 'Петр', 'surname' => 'Петров', 'patronymic' => 'Петрович'];
echo $user ['name'] . ' ' . $user ['surname'] . ' ' . $user ['patronymic'];
echo '<br>';
$date = ['year' => 2023, 'month' => 05, 'day' => 14];
echo $date['year'] . '-' . $date['month'] . '-' . $date['day'];
echo '<br>';
$arr = [7 => 'value1', 50 => 'value2', 23 => 'value3'];
echo $arr[23];
echo '<br>';
$arr = ['a', 'b', 'c', 'd', 'e', 'f'];
echo count($arr);
echo '<br>';
$arr = ['a' => 1, 'b' => 2, 'c' => 3, 'd' => 4];
echo count($arr);
echo '<br>';
$arr = ['a', 'b', 'c', 'd', 'e'];
echo $arr[count($arr)-2];
echo '<br>';
$arr = ['a' => 1, 'b' => 2, 'c' => 3];
$arr['a'] = 8;
$arr['b'] = 7;
$arr['c'] = 6;
var_dump($arr);
echo '<br>';
$arr = ['a' => 1, 'b' => 2, 'c' => 3];
$arr['a'] += 3;
$arr['b'] += 3;
$arr['c'] += 3;
var_dump($arr);
echo '<br>';
$arr = [];
$arr[] = 1;
$arr[] = 2;
$arr[] = 3;
$arr[] = 4;
$arr[] = 5;
var_dump($arr);
echo '<br>';
$arr = [1, 2, 3];
$arr[] = 4;
$arr[] = 5;
var_dump($arr);
echo '<br>';
$arr = [];
$arr['year'] = 2023;
$arr['month'] = 05;
$arr['day'] = 14;
var_dump($arr);
echo '<br>';
$arr = [1, 2, 3, 4, 5];
$key1 = 1;
$key2 = 2;
$result = $arr[$key1] + $arr[$key2];
echo $result;
echo '<br>';
$arr = ['a' => 1, 'b' => 2, 'c' => 3];
$key = 'c';
echo $arr[$key];
?>